In [1]:
import numpy as np

In [5]:
V = np.random.randn(20, 2)

In [6]:
V

array([[ 0.70419763,  0.95632104],
       [-1.60827879,  1.19743597],
       [-1.48301582,  1.48473068],
       [ 0.94564043, -0.25336536],
       [ 1.35411501,  0.57655879],
       [-0.51661998,  0.33678214],
       [-0.77290705,  0.93649795],
       [ 0.02478293, -0.65042375],
       [ 1.1553246 ,  0.02710721],
       [ 0.63395499,  0.69181196],
       [-0.13330322,  0.3772984 ],
       [-0.79109313,  0.99777706],
       [-0.91749188,  1.34811638],
       [ 0.4030224 , -0.14614595],
       [ 1.67995567,  1.35105513],
       [ 0.29528598, -0.47263212],
       [-0.08545446,  0.56837518],
       [ 0.25759633, -0.08832684],
       [ 1.91925758,  0.18287218],
       [ 0.63563859, -0.06881461]])

In [11]:
np.random.rand()

0.2746160277853714

In [13]:
colorList=[]
colorList .append( list(np.random.choice(range(256), size=3)) )

In [14]:
colorList

[[106, 175, 198]]

In [15]:
np.random.rand(3,)

array([0.7730037 , 0.80048755, 0.71839203])

In [20]:
np.random.choice([0,1],1)

array([0])